/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as DropsRouteImport } from './routes/drops'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const DropsRoute = DropsRouteImport.update({
  id: '/drops',
  path: '/drops',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/drops': typeof DropsRoute
  '/pedidos': typeof PedidosRoute
  '/perfil': typeof PerfilRoute
  '/sobre': typeof SobreRoute
  '/api/chat': typeof ApiChatRoute
  '/produto/$id': typeof ProdutoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/drops': typeof DropsRoute
  '/pedidos': typeof PedidosRoute
  '/perfil': typeof PerfilRoute
  '/sobre': typeof SobreRoute
  '/api/chat': typeof ApiChatRoute
  '/produto/$id': typeof ProdutoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/drops': typeof DropsRoute
  '/pedidos': typeof PedidosRoute
  '/perfil': typeof PerfilRoute
  '/sobre': typeof SobreRoute
  '/api/chat': typeof ApiChatRoute
  '/produto/$id': typeof ProdutoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/contato'
    | '/drops'
    | '/pedidos'
    | '/perfil'
    | '/sobre'
    | '/api/chat'
    | '/produto/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/contato'
    | '/drops'
    | '/pedidos'
    | '/perfil'
    | '/sobre'
    | '/api/chat'
    | '/produto/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/contato'
    | '/drops'
    | '/pedidos'
    | '/perfil'
    | '/sobre'
    | '/api/chat'
    | '/produto/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CatalogoRoute: typeof CatalogoRoute
  CheckoutRoute: typeof CheckoutRoute
  ContatoRoute: typeof ContatoRoute
  DropsRoute: typeof DropsRoute
  PedidosRoute: typeof PedidosRoute
  PerfilRoute: typeof PerfilRoute
  SobreRoute: typeof SobreRoute
  ApiChatRoute: typeof ApiChatRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drops': {
      id: '/drops'
      path: '/drops'
      fullPath: '/drops'
      preLoaderRoute: typeof DropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CarrinhoRoute: CarrinhoRoute,
  CatalogoRoute: CatalogoRoute,
  CheckoutRoute: CheckoutRoute,
  ContatoRoute: ContatoRoute,
  DropsRoute: DropsRoute,
  PedidosRoute: PedidosRoute,
  PerfilRoute: PerfilRoute,
  SobreRoute: SobreRoute,
  ApiChatRoute: ApiChatRoute,
  ProdutoIdRoute: ProdutoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
